apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cotm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0092-tenant/ci1t-43256-0092-app/devfile-sample-cotm@sha256:07464cb20ee77cc920da7b475c3f8cc54abfab03a1351b14d6ea8e9d6e9bac8d
        name: my-nodejs
        resources: {}
status: {}
