apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cotm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cotm
    app.kubernetes.io/part-of: ci1t-43256-0092-app
  name: devfile-sample-cotm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cotm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cotm
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0092-tenant/ci1t-43256-0092-app/devfile-sample-cotm@sha256:07464cb20ee77cc920da7b475c3f8cc54abfab03a1351b14d6ea8e9d6e9bac8d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
